#!/bin/bash

echo "🎯 ASK CLAUDE QUESTIONS - MANUAL GUIDE"
echo "======================================"
echo ""
echo "📝 HOW TO ASK CLAUDE QUESTIONS:"
echo ""
echo "1. Get your Claude API key from: https://console.anthropic.com/"
echo ""
echo "2. Edit .env file and replace:"
echo "   ANTHROPIC_API_KEY=your_real_key_here_later"
echo "   with your actual key"
echo ""
echo "3. Restart server: npm start"
echo ""
echo "4. Ask questions like this:"
echo ""
echo "curl -X POST -H \"x-api-key: test123\" \\"
echo "  -H \"Content-Type: application/json\" \\"
echo "  -d '{\"question\":\"Should I buy BTC now?\", \"symbol\":\"BTCUSDT\"}' \\"
echo "  http://localhost:3000/mcp/ask-claude"
echo ""
echo "📊 SAMPLE QUESTIONS:"
echo "- Should I buy BTC now?"
echo "- What's the current market sentiment?"
echo "- Analyze the order book"
echo "- What technical patterns do you see?"
echo "- How volatile is the market?"
echo ""
echo "🔥 CLAUDE SEES LIVE DATA:"
echo "- Real-time price & 24h stats"
echo "- Order book (bids/asks)"
echo "- Recent trades"
echo "- Price chart (last 10 hours)"
echo ""
echo "⚡ TEST MARKET DATA NOW (works without API key):"
curl -H "x-api-key: test123" http://localhost:3000/mcp/market-data/BTCUSDT | jq '.currentPrice, .stats.priceChangePercent' 2>/dev/null || echo "Install jq for pretty output, but data is there!"